# Generated by Django 4.1.5 on 2024-02-14 07:22

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=256,
                null=True,
                upload_to=backend.models.Product.get_file_path,
                verbose_name="Постер",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Фото"
            ),
        ),
    ]
