# Generated by Django 4.1.5 on 2024-02-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_product_photo_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Фото"
            ),
        ),
    ]
